
key = dict(
    q1 = dict(entrytype='var', pts=4, auto=True,
              answers=["c) Maine"],
              question="Which State is represented in the plot."),
    q2 = dict(entrytype='cell', pts=6, auto=False,
              question="Write code to recreate the above plot, but with a title."),
    q3 = dict(entrytype='cell', pts=7, auto=False,
              question="Add a y-axis label to the plot."),
    q4 = dict(entrytype='cell', pts=5, auto=False,
              question="Plot a histogram of new cases across all states."),
    q5 = dict(entrytype='var', pts=5, auto=True, answers=["b) California on January 10th, 2022"],
              question=" State/day has the highest single day new case count?"),
    q6a = dict(entrytype='var', pts=2, auto=True, answers=[0.0],
              question="fill in the blanks for mean new cases: American Samoa"),
    q6b = dict(entrytype='var', pts=2, auto=True, answers=[1138.0],
              question="fill in the blanks for mean new cases: Arkansas"),
    q6c = dict(entrytype='var', pts=2, auto=True, answers=[1813.7],
              question="fill in the blanks for mean new cases: Colorado"),
    q7 = dict(entrytype='var', pts=7, auto=False,
              question="how might you get per capita case counts"),
    q8 = dict(entrytype='cell', pts=10, auto=False,
              question="mimic the facetgrid chart."),
)