
key = dict(
    q1 = dict(entrytype='var', pts=3, auto=True,
              answers=["c) White/Female"],
              question="Which Race+Gender is represented in the plot."),
    q2 = dict(entrytype='cell', pts=5, auto=False,
              question="Write code to recreate the above plot, but with a title."),
    q3 = dict(entrytype='cell', pts=6, auto=False,
              question="Add a y-axis label to the plot."),
    q4 = dict(entrytype='cell', pts=4, auto=False,
              question="Plot a histogram of the life expectancy values across all conditions and years."),
    q5 = dict(entrytype='var', pts=4, auto=True, answers=["c) Black Male in 1904"],
              question=" Which Race+Sex group had the lowest life expectancy, and in what year?"),
    q6a = dict(entrytype='var', pts=2, auto=True, answers=[66.9],
              question="fill in the blanks for mean life expectancy - all/all"),
    q6b = dict(entrytype='var', pts=2, auto=True, answers=[56.2],
              question="fill in the blanks for mean life expectancy: black/male"),
    q6c = dict(entrytype='var', pts=2, auto=True, answers=[70.3],
              question="fill in the blanks for mean life expectancy: white/female"),
    q7 = dict(entrytype='var', pts=7, auto=False,
              question="how might you get average life expectancy by decade"),
    q8 = dict(entrytype='cell', pts=10, auto=False,
              question="mimic the facetgrid chart."),
)